### ISSUE TITLE
Erro gramatical no título.

### ISSUE THREAD

**Issue by JeffersonAmori** [dotnet/AspNetCore.Docs.pt-br#121]
No título em pt-br "Empacotar e reduzirr ativos estáticos no ASP.NET Core" há um 'R' a mais na palavra reduzir.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Empacotar e reduzirr ativos estáticos no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @JeffersonAmori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
