### ISSUE TITLE
Documentação desatualizada

### ISSUE THREAD

**Issue by Hitmasu** [dotnet/AspNetCore.Docs.pt-br#129]
Na parte de configuração do JSON, existem locais que estão apontando para **_SerializerOptions_** (Newtonsoft). O correto deveria ser  [JsonSerializerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.jsonoptions.jsonserializeroptions?view=aspnetcore-3.1), pois no contexto é utilizado exclusivamente o namespace `System.Text.Json`. Para poder utilizar o SerializerOptions, é necessário fazer a referência ao package  [NewtonsoftJson](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/), que é feito no tópico em seguida.

Ao invés de **_JsonOptions.SerializerOptions_**, o correto seria **_JsonOptions.JsonSerializerOptions_**:

```csharp

services.AddControllers().AddJsonOptions(options =>
{
    // Use the default property (Pascal) casing.
    options.SerializerOptions.PropertyNamingPolicy = null;

    // Configure a custom converter.
    options.SerializerOptions.Converters.Add(new MyCustomJsonConverter());
});
```
->

```csharp
services.AddControllers().AddJsonOptions(options =>
{
    // Use the default property (Pascal) casing.
    options.JsonSerializerOptions.PropertyNamingPolicy = null;

    // Configure a custom converter.
    options.JsonSerializerOptions.Converters.Add(new MyCustomJsonConverter());
});
```
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Formatar dados de resposta na API Web ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Hitmasu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Hitmasu** [comment]
#130

**Comment by CeciAc** [comment]
Issue moved to [dotnet/AspNetCore.Docs #17691](https://github.com/dotnet/AspNetCore.Docs/issues/17691) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Olá, @Hitmasu,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/dotnet/AspNetCore.Docs/issues/17691.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
