### ISSUE TITLE
Error ao implementar DTO no Controller

### ISSUE THREAD

**Issue by pinkblez** [dotnet/AspNetCore.Docs.pt-br#133]
Seguindo os passos do tutorial "Criar uma API Web" me surgiu alguns erros que não consegui compreender inicialmente. Ao criar o TodoItemDTO e fazer as alterações no Controller, apareceu os seguintes erros:

The name 'ItemToDTO' does not exist in the current context [TodoApi]csharp(CS0103)
The name 'TodoItemExists' does not exist in the current context [TodoApi]csharp(CS0103)
This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [TodoApi]csharp(CS1998)
'TodoItemsController.PostTodoItem(TodoItemDTO)': not all code paths return a value [TodoApi]csharp(CS0161)

E por aí vai.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: criar uma API Web com ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @pinkblez
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pinkblez 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/18152

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
