### ISSUE TITLE
Attributo CreditCard precisa de scripts adicionais 

### ISSUE THREAD

**Issue by andrebaltieri** [dotnet/AspNetCore.Docs.pt-br#134]
Para utilizar a validação no lado do cliente com o atributo CreditCard você precisa referenciar o jQuery Validation Additional Methods que pode ser encontrado aqui:: https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js

Sempre cheque as versões mais recentes dos scripts do jQuery Validation no site oficial::
https://jqueryvalidation.org/

---

In order to have client-side validation using the CreditCard attribute you need to reference jQuery Validation Additional Methods scipts, which can be found here: https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js

Consider checking the latest scripts version on jQuery Validation official website:
https://jqueryvalidation.org/

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Validação de modelo no ASP.NET Core MVC](https://docs.microsoft.com/pt-br/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@CeciAc move this to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by Rick-Anderson** [comment]
@CeciAc  it looks like this was automatically moved. 
The same thing happened with https://github.com/dotnet/AspNetCore.Docs/issues/18150 and https://github.com/dotnet/AspNetCore.Docs/issues/18146

**Comment by srvbpigh** [comment]
Hello, @andrebaltieri
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
