### ISSUE TITLE
Not function on .NET code 5.0 preview

### ISSUE THREAD

**Issue by ajmatos** [dotnet/AspNetCore.Docs.pt-br#136]
Not function on .NET code 5.0 preview.
Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [TodoApi]

.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v5.0", FrameworkDisplayName = "")]

---

Wen I try install packages:
PS C:\_DADOS\Projetos\quickstart\TodoApi> dotnet add package Microsoft.EntityFrameworkCore.Design
  Determining projects to restore...
  Writing C:\Users\anton\AppData\Local\Temp\tmpDDFF.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.Design' into project 'C:\_DADOS\Projetos\quickstart\TodoApi\TodoApi.csproj'.
info : Restoring packages for C:\_DADOS\Projetos\quickstart\TodoApi\TodoApi.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/index.json 880ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/3.1.4/microsoft.entityframeworkcore.design.3.1.4.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/3.1.4/microsoft.entityframeworkcore.design.3.1.4.nupkg 38ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.csharp/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.csharp/index.json 594ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.csharp/4.7.0/microsoft.csharp.4.7.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.csharp/4.7.0/microsoft.csharp.4.7.0.nupkg 30ms
info : Installing Microsoft.CSharp 4.7.0.
info : Installing Microsoft.EntityFrameworkCore.Design 3.1.4.
info : Package 'Microsoft.EntityFrameworkCore.Design' is compatible with all the specified frameworks in project 'C:\_DADOS\Projetos\quickstart\TodoApi\TodoApi.csproj'.
odoApi\TodoApi.csproj'.
info : Committing restore...
info : Generating MSBuild file C:\_DADOS\Projetos\quickstart\TodoApi\obj\TodoApi.csproj.nuget.g.props.
log  : Restored C:\_DADOS\Projetos\quickstart\TodoApi\TodoApi.csproj (in 2.77 sec).
PS C:\_DADOS\Projetos\quickstart\TodoApi> dotnet tool install --global dotnet-aspnet-codegenerator
You can invoke the tool using the following command: dotnet-aspnet-codegenerator
Tool 'dotnet-aspnet-codegenerator' (version '3.1.3') was successfully installed.
PS C:\_DADOS\Projetos\quickstart\TodoApi> dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0-preview3.19553.2' was not found.
  - The following frameworks were found:
      5.0.0-preview.3.20214.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0-preview3.19553.2&arch=x64&rid=win10-x64 
PS C:\_DADOS\Projetos\quickstart\TodoApi>

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: criar uma API Web com ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @ajmatos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ajmatos 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@ajmatos  sorry for this problem. The document has not been updated to .NET code 5.0 preview
