### ISSUE TITLE
Translate of Cookie Term in PT-BR is wrong.

### ISSUE THREAD

**Issue by rafaelcruz-net** [dotnet/AspNetCore.Docs.pt-br#139]
Guys,

In this page https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1, the translate of term cookie is wrong. 

The page show the translate "ARAR" on state managment table in PT-BR but the correct is Cookie. 

In PT-BR we dont translate the term Cookie. We can use cookie in the natural form.

Thanks

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Sessão no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think we should probably code fence cookie everywhere so it's not translated. I'm guessing most languages don't translate it.
cc @scottaddie @guardrex

**Comment by Rick-Anderson** [comment]
[77 results for "cookie" in ASP.NET Core Documentation](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-3.1&terms=cookie&category=Documentation)

cc @JasonCard

**Comment by guardrex** [comment]
I recommend adding this one to the metadata list ... doesn't it look really funky in code style?

**Comment by Rick-Anderson** [comment]
>I recommend adding this one to the metadata list

Yes, and that's easier and should be safer. To bad the  metadata list is so clucky (list per file).

**Comment by guardrex** [comment]
Find and replace. It's *mostly* stable. If we don't keep the terms in alphabetical order, it will always be super easy to add new terms.

Find ...

```
no-loc: [
```

... replace ...

```
no-loc: [cookie, 
```

(a space is on the end of that)

**Comment by JasonCard** [comment]
Although, I found that "cookie" can be localized in a couple of languages, it should be left in English for most languages. And it's better to leave them in English then having them incorrectly machine translated. So I agree with the solution to use the no-loc metadata. However, please note that no-loc metadata is case sensitive, so if both "cookie" and "Cookie" is used, then both should be added.

**Comment by Rick-Anderson** [comment]
Thanks @JasonCard , we'll include both. Can you transfer this issue to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by JasonCard** [comment]
Transferring issue to [https://github.com/dotnet/AspNetCore.Docs/issues/19431](https://github.com/dotnet/AspNetCore.Docs/issues/19431) and closing this one.

**Comment by rafaelcruz-net** [comment]
Thanks guys. 
Let me know about the resolution of this issue
