### ISSUE TITLE
Translation of the term "Models" to "Modelos" in PT-BR

### ISSUE THREAD

**Issue by lucasfreitas-dev** [dotnet/AspNetCore.Docs.pt-br#142]
Hi,

In some instructions of the guide the folder "Models" has been translated to "Modelos", but the same word in the code has not, this can cause erros during the implementation.

The word "Models" should be perseved in english whenever used as folder name.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: criar uma API Web com ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JasonCard  transfer this and I'll code fence where `Models` is used as the folder name.

**Comment by JasonCard** [comment]
@Rick-Anderson Thank you, opened [https://github.com/dotnet/AspNetCore.Docs/issues/19802](https://github.com/dotnet/AspNetCore.Docs/issues/19802). 

@lucasfreitas-dev Thank you for your feedback and we will address this issue by blocking the term "Models" from translation.
